@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.arsmagica2.arsmagica2return.client.gui.inscriptiontable.colorpicker;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
