@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.arsmagica2.arsmagica2return.client.hud;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;