@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.arsmagica2.arsmagica2return;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
