@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.arsmagica2.arsmagica2return.common.block.sign;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;