@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.arsmagica2.arsmagica2return.common.util;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;